# Generated by Django 5.2.3 on 2025-06-28 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='duration_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Start-End Date')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(default='My Budget', max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='type',
            field=models.CharField(choices=[('salary', 'Salary'), ('saving', 'Saving'), ('custom', 'Custom')], default='salary', max_length=10),
        ),
    ]
