# Generated by Django 5.2.3 on 2025-06-28 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_expense_user_alter_expense_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='duration_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Start-End Date')], max_length=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='type',
            field=models.CharField(choices=[('salary', 'Salary'), ('saving', 'Saving'), ('custom', 'Custom')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('one-time', 'One-Time')], max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
